auto: true
markdown: kramdown
kramdown:  
    parse_block_html: true
rdiscount extensions: [smart]
sass:
    style: expanded
    sass_dir: css/_sass
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.txt"
    - "*.enc"
    - vendor
plugins:
    - jekyll-autoprefixer
autoprefixer:
    browsers:
        - last 2 versions