weaviate_version: 0.8.6
auto: true
markdown: kramdown
kramdown:  
    parse_block_html: false
rdiscount extensions: [smart]
sass:
    style: compressed # opposed to "expanded"
    sass_dir: css/_sass
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.txt"
    - "*.enc"
    - vendor
    - README.md
plugins:
    - jekyll-autoprefixer
autoprefixer:
    browsers:
        - last 2 versions